[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enterprise_tools"              # 包名（pip install 后导入的名字）
version = "0.1.0"
description = "企业级大模型工具集：摘要、情感分类、润色、Text-to-SQL 等"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "ynh", email = "17555277581@163.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
    "openai",
    "python-dotenv",
    "instructor",
    "pydantic",
]
[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]